In [1]:
import numpy as np

In [4]:
an_array = np.array([[11, 12, 13, 14],
                   [21, 22, 23, 24],
                   [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [6]:
a_slice = an_array[:2, 1:3]
a_slice

array([[12, 13],
       [22, 23]])

In [7]:
a_slice[0, 0] += 1000
print(a_slice)
print(an_array)

[[1012   13]
 [  22   23]]
[[  11 1012   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


In [14]:
an_array = np.array([[11, 12, 13, 14],
                   [21, 22, 23, 24],
                   [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
a_slice = an_array[:2, 1:3]
a_slice

array([[12, 13],
       [22, 23]])

In [16]:
another_slice = np.array(an_array[:2, 1:3])
another_slice

array([[12, 13],
       [22, 23]])

In [17]:
another_slice[0, 0] += 1000
print(another_slice)
print()
print(an_array)

[[1012   13]
 [  22   23]]

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
