In [13]:
import numpy as np

In [4]:

an_array = np.array([[11, 12],
                   [21, 22],
                   [31, 33]])
print(an_array)

[[11 12]
 [21 22]
 [31 33]]


In [5]:
_filter = an_array > 15

In [6]:
_filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [7]:
an_array[_filter]

array([21, 22, 31, 33])

In [14]:
an_array[an_array > 15]

array([21, 22, 31, 33])

In [17]:
# an_array[an_array > 20 & an_array < 30]

In [18]:
an_array[an_array %2 == 0] += 100

In [ ]:
an_array