<a href = https://prod-edxapp.edx-cdn.org/assets/courseware/v1/26fe28d6499a2edb739a4af78ff93a0b/asset-v1:UCSanDiegoX+DSE200x+2T2017+type@asset+block/W3_L2_V1_why_numpy.pdf>Link<a/>

In [1]:
import numpy as np

In [2]:
an_array = np.array([3, 33, 333])
an_array

array([  3,  33, 333])

In [3]:
type(an_array)

numpy.ndarray

In [4]:
an_array.shape

(3,)

In [5]:
an_array[1], an_array[1], an_array[2]

(33, 33, 333)

In [6]:
an_array[0] = 888
an_array

array([888,  33, 333])

In [7]:
rank_2_array = np.array([[0, 1, 2],
                         [11, 12, 13]])

In [8]:
rank_2_array

array([[ 0,  1,  2],
       [11, 12, 13]])

In [9]:
rank_2_array[0]

array([0, 1, 2])

In [10]:
rank_2_array[0][0]

0

In [11]:
rank_2_array[1]

array([11, 12, 13])

In [12]:
rank_2_array[1][2]

13

In [13]:
rank_2_array.shape

np.zeros((3, 4))

np.full((4, 3), 14)

array([[14, 14, 14],
       [14, 14, 14],
       [14, 14, 14],
       [14, 14, 14]])

In [14]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.ones((5, 4, ))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
ar = np.random.random((3,4))
ar

array([[0.61242713, 0.58003095, 0.31054248, 0.46793873],
       [0.33531191, 0.60917887, 0.84703758, 0.5613004 ],
       [0.15891396, 0.19669075, 0.36323103, 0.09237181]])

In [17]:
a_slice = ar[:2, 1:3]
a_slice

array([[0.58003095, 0.31054248],
       [0.60917887, 0.84703758]])

In [18]:
a_slice[0, 0]

0.5800309541298833

In [21]:
an_array = np.array([
    ["01", "02", "03", "04"],
    [11, 12, 13, 14],
    [21, 22, 23, 24]
    
])
an_array

array([['01', '02', '03', '04'],
       ['11', '12', '13', '14'],
       ['21', '22', '23', '24']], dtype='<U2')

In [24]:
a_slice = an_array[:2, 1:3]
a_slice

array([['02', '03'],
       ['12', '13']], dtype='<U2')

In [25]:
a_slice[0, 0]

'02'

In [27]:
a_slice[0, 0] = "x"
a_slice

array([['x', '03'],
       ['12', '13']], dtype='<U2')

In [28]:
an_array

array([['01', 'x', '03', '04'],
       ['11', '12', '13', '14'],
       ['21', '22', '23', '24']], dtype='<U2')

In [29]:
a_slice[0, 0] = "02"
a_slice 

array([['02', '03'],
       ['12', '13']], dtype='<U2')

In [31]:

a_slice = np.array(an_array  [:2, 1:3])

In [32]:
a_slice

array([['02', '03'],
       ['12', '13']], dtype='<U2')

In [34]:
a_slice[0, 0] = "x"
a_slice

array([['x', '03'],
       ['12', '13']], dtype='<U2')

In [35]:
an_array

array([['01', '02', '03', '04'],
       ['11', '12', '13', '14'],
       ['21', '22', '23', '24']], dtype='<U2')

In [37]:
row_rank1 = an_array[1, :]
row_rank1

array(['11', '12', '13', '14'], dtype='<U2')

In [38]:
row_rank1.shape

(4,)

In [41]:
row_rank2 = an_array[1:2, :]
row_rank2

array([['11', '12', '13', '14']], dtype='<U2')

In [42]:
row_rank2.shape

(1, 4)

In [61]:
an_array = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33],
    [41, 42, 43],
])

In [62]:
an_array

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [63]:
col_indices = np.array([0, 1, 2, 0])
col_indices

array([0, 1, 2, 0])

In [64]:
row_indices = np.arange(4)
row_indices

array([0, 1, 2, 3])

In [65]:
for row, col in zip(row_indices, col_indices):
    print(row, ',', col)

0 , 0
1 , 1
2 , 2
3 , 0


In [66]:
ar = an_array[row_indices, col_indices]
ar

array([11, 22, 33, 41])

In [70]:
an_array[row_indices, col_indices] += 1000
an_array

array([[3011,   12,   13],
       [  21, 3022,   23],
       [  31,   32, 3033],
       [3041,   42,   43]])