In [1]:
# source("http://bioconductor.org/biocLite.R")
# biocLite("rhdf5")

In [2]:
library(rhdf5)
# created = h5cr

In [3]:
created = h5createFile("example.h5")
created

[1] TRUE

In [6]:
created = h5createGroup('example.h5', 'foo')
created = h5createGroup('example.h5', 'baa')
created = h5createGroup('example.h5', 'foo/foobaa')
h5ls("example.h5")

Can not create group. Object with name 'foo' already exists.
Can not create group. Object with name 'baa' already exists.
Can not create group. Object with name 'foo/foobaa' already exists.


group name   otype     dclass dim
0 /     baa    H5I_GROUP           
1 /     foo    H5I_GROUP           
2 /foo  foobaa H5I_GROUP

In [8]:
A = matrix(1:10, nr=5, nc=2)
h5write(A, "example.h5", 'foo/A')
B = array(seq(0.1, 2.0, by=0.1), dim = c(5, 2, 2))
attr(B, "scale") <- "liter"
h5write(B, "example.h5", "foo/foobaa/B")
h5ls("example.h5")

group       name   otype       dclass  dim      
0 /           baa    H5I_GROUP                    
1 /           foo    H5I_GROUP                    
2 /foo        A      H5I_DATASET INTEGER 5 x 2    
3 /foo        baa    H5I_DATASET INTEGER 5 x 2    
4 /foo        foobaa H5I_GROUP                    
5 /foo/foobaa B      H5I_DATASET FLOAT   5 x 2 x 2

In [9]:
df = data.frame(1L:5L, 
                seq(0, 1, length.out = 5),
                c('ab', 'cde', 'fghi', 'a', 's'), 
                stringsAsFactors=FALSE)
h5write(df, "example.h5", "df")
h5ls("example.h5")

group       name   otype       dclass   dim      
0 /           baa    H5I_GROUP                     
1 /           df     H5I_DATASET COMPOUND 5        
2 /           foo    H5I_GROUP                     
3 /foo        A      H5I_DATASET INTEGER  5 x 2    
4 /foo        baa    H5I_DATASET INTEGER  5 x 2    
5 /foo        foobaa H5I_GROUP                     
6 /foo/foobaa B      H5I_DATASET FLOAT    5 x 2 x 2

In [10]:
readA = h5read("example.h5", 'foo/A')
readB = h5read("example.h5", 'foo/foobaa/B')
readdf = h5read("example.h5", 'df')


In [11]:
readA

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [12]:
h5write(c(12, 13, 14), 'example.h5', 'foo/A', index=list(1:3, 1))
h5read("example.h5", 'foo/A')

[,1] [,2]
[1,] 12    6  
[2,] 13    7  
[3,] 14    8  
[4,]  4    9  
[5,]  5   10

In [13]:
h5write(c(12, 13, 14), 'example.h5', 'foo/A', index=list(3:5, 2))
h5read("example.h5", 'foo/A')

[,1] [,2]
[1,] 12    6  
[2,] 13    7  
[3,] 14   12  
[4,]  4   13  
[5,]  5   14

In [14]:
h5write(c(12, 13, 14), 'example.h5', 'foo/A', index=list(2:4, 3))
h5read("example.h5", 'foo/A')

[,1] [,2]
[1,] 12    6  
[2,] 13    7  
[3,] 14   12  
[4,]  4   13  
[5,]  5   14

In [15]:
h5read("example.h5", 'foo/A', index = list(1:3, 2))

[,1]
[1,]  6  
[2,]  7  
[3,] 12