https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np
print(np.__version__)

1.15.3


In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
arr = np.arange(10)
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [6]:
arr = np.arange(10)
arr[arr % 2 != 0 ] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
arr = np.arange(10)
ans = np.where(arr % 2 != 0, -1, arr)
print(arr)
print(ans)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
arr = np.arange(10)
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [14]:
np.concatenate([a, b], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.concatenate([a, b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
a = np.array([1, 2, 3])

In [33]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3])

In [31]:
np.tile(a, 6)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
np.r_[np.repeat(a, 5), np.tile(a, 3)]

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3])

In [35]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

In [38]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [41]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10) ]

array([ 6,  9, 10])

In [45]:
a[np.where((a >= 5) & (a <= 10))]

array([ 6,  9, 10])

In [47]:
index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]

array([ 6,  9, 10])

In [76]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(min, otypes = [float])
print(pair_max(a, b))

[5. 3. 4. 8. 6. 4. 1.]
